export { CommitAttachmentIn } from './commitAttachment';
export { LinkAttachmentsIn } from './linkAttachments';
export { NewAttachmentIn, NewAttachmentOut } from './newAttachment';
export { ResponsePendencyIn } from './responsePendency';
export { SearchTasksIn, SearchTasksOut } from './searchTasks';
export { StartProcessIn, StartProcessOut } from './startProcess';
export { StartRequestIn, StartRequestOut } from './startRequest';
export { FindProcessIn, FindProcessOut } from './findProcess';
export { GetProcessesListIn, GetProcessesListOut } from './getProcessesList';
export { GetRankingProcessesIn, GetRankingProcessesOut } from './getRankingProcesses';
export { GetProcessInstanceIn, GetProcessInstanceOut } from './getProcessInstance';
export { CancelProcessInstanceIn } from './cancelProcessInstance';
export { GetRequestsResumeIn, GetRequestsResumeOut } from './getRequestsResume';
export { GetRequestHistoryTimelineIn, GetRequestHistoryTimelineOut } from './getRequestHistoryTimeline';
export { GetThirdPartyRequestByStatusIn, GetThirdPartyRequestByStatusOut } from './getThirdPartyRequestByStatus';
export { GetSubjectsIn, GetSubjectsOut } from './getSubjects';
export { GetNextSubjectIn, GetNextSubjectOut } from './getNextSubject';
export { GetNextSubjectFromInitialTaskIn, GetNextSubjectFromInitialTaskOut } from './getNextSubjectFromInitialTask';
export { BatchPendenciesResponseIn } from './batchPendenciesResponse';
export { ChangePendencyUserIn } from './changePendencyUser';
export { GetPendencyProcessActionsIn, GetPendencyProcessActionsOut } from './getPendencyProcessActions';
export { GetMyPendenciesIn, GetMyPendenciesOut } from './getMyPendencies';
